"use strict";

const API = "https://plcjkuhxtodofyjnusjf.supabase.co/functions/v1/admin";
// XML namespace for createElementNS. Not a network address — nothing is fetched from it.
const SVG_NS = "http://www.w3.org/2000/svg";
const RESPONSE_STATUS = { success: 200, bad_request: 400, unauthorized: 401, forbidden: 403, not_found: 404, rate_limited: 429, internal: 500, upstream_unavailable: 503 };

const strings = {
  ru: {
    app_title: "Панель GAUDI", loading: "Загружаю…", today_dialogs: "Диалогов сегодня", owner: "Владелец", manager: "Менеджер", unknown_role: "Сотрудник",
    not_telegram: "Откройте панель из Telegram", unauthorized: "Не удалось подтвердить вход. Откройте панель заново из Telegram.", forbidden: "Нет доступа. Панель только для сотрудников GAUDI.", origin_denied: "Нет доступа. Панель только для сотрудников GAUDI.", not_found: "Раздел не найден.", bad_request: "Неверный период. Проверьте даты.", rate_limited: "Слишком много запросов. Подождите минуту.", upstream_unavailable: "Сервис временно недоступен, попробуйте ещё раз.", internal: "На нашей стороне что-то пошло не так.", retry: "Повторить",
    period: "Период", days_7: "7 дней", days_30: "30 дней", days_90: "90 дней", custom: "Произвольный", from: "С", to: "По", channel: "Канал", manager_filter: "Менеджер", all: "Все", telegram: "Telegram", whatsapp: "WhatsApp", web: "Web", email: "E-mail", invalid_period: "Неверный период. Проверьте даты.",
    volume: "Диалоги", volume_note: "Сколько людей написали боту и сколько сообщений прошло.", dialogs: "Диалогов", dialogs_hint: "людей, написавших хотя бы одно сообщение", client_messages: "Сообщений от клиентов", bot_messages: "Ответов бота", manager_messages: "Сообщений менеджеров", new_leads: "Новых клиентов", new_leads_hint: "первое обращение за период", volume_chart: "Диалоги по дням и каналам",
    funnel: "Воронка", funnel_note: "Путь клиента от первого сообщения до закрытия. Считается по когорте: клиент учитывается в том дне, когда написал впервые.", leads_total: "Написали", leads_total_hint: "всего клиентов за период", engaged: "Дошли до разговора", engaged_hint: "бот ответил хотя бы раз", with_contact: "Оставили контакт", with_contact_hint: "телефон или почта, пригодные для связи", with_cart: "Дошли до корзины", funnel_closed: "Закрыты менеджером", share_of_all: "от всех написавших", to_previous: "к предыдущей ступени", previous_empty: "предыдущая ступень пуста", funnel_note_bottom: "Ступени не строго вложены: клиент может дойти до корзины, не оставив контакт, — поэтому доля от всех клиентов надёжнее, чем конверсия к предыдущей.", funnel_channels: "По каналам",
    web_events: "Виджет на сайте", web_note: "Действия в чате на сайте. Это только окно чата — кнопки контактов и корзина самого сайта сюда не попадают", web_chart: "Действия в чате по дням", launcher_click: "Кликнули по кнопке чата", invite_click: "Кликнули по всплывающей подсказке", web_open: "Запустили чат", consent_ok: "Согласились и начали диалог", contact_open: "Раскрыли форму контактов", contact_email: "Оставили почту", contact_phone: "Оставили телефон", file_upload: "Отправили фото", telegram_click: "Перешли в Telegram", cart_click: "Открыли корзину из ответа бота",
    carts: "Корзины", carts_note: "Попытки собрать корзину на сайте от имени клиента.", sent: "Собрано корзин", error: "Сайт не принял", error_hint: "ошибка на стороне сайта", empty_cart: "Нечего было класть", empty_cart_hint: "ни один артикул не нашёлся в каталоге сайта", items_total: "Позиций всего",
    managers: "Менеджеры", managers_note: "Передача диалогов людям и скорость реакции.", manager_open: "Открытых обращений", manager_closed: "Закрытых", claimed: "Взяты в работу", unclaimed: "Никто не взял", claim_p50: "Половина обращений берут быстрее", close_p50: "Половина закрывают быстрее", measured_threads: "посчитано по {n} обращениям из {m}", manager_name: "Менеджер", replies: "Ответов", threads_claimed: "Взял обращений", last_reply: "Последний ответ",
    cost: "Расход", cost_note: "Сколько стоит работа бота и как быстро он отвечает.", estimated_cost: "Примерная стоимость", cost_range_note: "диапазон, потому что часть запроса попадает в кеш и стоит в десять раз дешевле, а сколько именно — поставщик не сообщает. Правда ближе к нижней границе.", priced_coverage: "посчитано по {n} ответам из {m}", unpriced_coverage: "для {n} ответов цена модели неизвестна", tokens_in: "Отправлено боту", tokens_out: "Написано ботом", tokens_note: "Отправлено во много раз больше — это нормально: инструкция бота уходит целиком при каждом обращении к модели, а ответ короткий.", calls_per_answer: "Обращений к модели на один ответ", calls_hint: "ответ с поиском по каталогу стоит двух обращений", measured_answers: "посчитано по {n} ответам", latency_p50: "Половина ответов быстрее", latency_p95: "Каждый двадцатый дольше", speed_note: "Быстро — до 5 секунд. Дольше 20 клиент обычно уже не ждёт.", cost_chart: "Токены по дням", models: "По моделям", model: "Модель", with_tokens: "С токенами",
    routing: "Как отвечал бот", routing_note: "Каким способом бот отвечал — от этого зависит и качество, и цена.", branches: "Способ ответа", route_reasons: "Почему выбран такой ответ", detailed_answer: "Подробный ответ", detailed_answer_hint: "дорогая модель, с поиском по каталогу", short_answer: "Короткий ответ", short_answer_hint: "дешёвая модель: приветствие, болтовня", followup_answer: "Напоминание", followup_answer_hint: "бот сам написал замолчавшему клиенту", other: "Прочее", show_all: "Показать все", route_sticky_product: "продолжение разговора о товаре", route_greeting: "приветствие", route_category: "спросили про категорию", route_article: "назвали артикул", route_order: "речь о заказе", route_long: "длинное сообщение", route_human: "нужен человек", route_default: "ничего особенного", route_followup_1: "напоминание, 1-е", route_followup_2: "напоминание, 2-е", route_followup_3: "напоминание, 3-е",
    dealers: "Дилеры", dealers_note: "Уведомления ответственным менеджерам по дилерским странам.", notifications: "Уведомлений отправлено", countries: "Стран", dealer_with_cart: "Из них с готовой корзиной", country: "Страна", ship_type: "Тип отгрузки", responsible: "Ответственный", last: "Последнее",
    geo: "География", geo_note: "Откуда клиенты и чем интересуются. Поля заполняет бот, поэтому пробелов много.", dealer: "Дилер", interests: "Интересы к товарам", product_interest: "Интерес", leads: "Клиентов", unknown_country: "без страны: {n}", unknown_dealer: "без дилера: {n}", unknown_interest: "без интереса: {n}",
    quality: "Качество", quality_note: "Жалобы на бота через команду /bug.", reports_total: "Всего жалоб", reports_open: "Не разобрано", statuses: "По статусам", categories: "По категориям", severities: "По серьёзности", status: "Статус", category: "Категория", severity: "Серьёзность", reports: "Жалобы",
    versions: "Версии бота", versions_note: "Что менялось в инструкции бота и как это сказалось на ответах.", prompt_version: "Версия", date: "Дата", latency: "Половина быстрее", main_share: "Доля подробных ответов", low_sample_note: "строки, где меньше 20 ответов, статистически ничего не значат", description_missing: "описание не сохранилось",
    no_data: "нет данных", no_period_data: "нет данных за период", hours_minutes: "{h} ч {m} мин", minutes: "{m} мин", seconds: "{s} сек", milliseconds: "{n} мс", percent: "{n}%"
  },
  en: {
    app_title: "GAUDI panel", loading: "Loading…", today_dialogs: "Dialogs today", owner: "Owner", manager: "Manager", unknown_role: "Team member",
    not_telegram: "Open the panel from Telegram", unauthorized: "We could not confirm your sign-in. Open the panel again from Telegram.", forbidden: "Access denied. This panel is for GAUDI staff only.", origin_denied: "Access denied. This panel is for GAUDI staff only.", not_found: "Section not found.", bad_request: "Invalid period. Check the dates.", rate_limited: "Too many requests. Please wait a minute.", upstream_unavailable: "The service is temporarily unavailable. Please try again.", internal: "Something went wrong on our side.", retry: "Retry",
    period: "Period", days_7: "7 days", days_30: "30 days", days_90: "90 days", custom: "Custom", from: "From", to: "To", channel: "Channel", manager_filter: "Manager", all: "All", telegram: "Telegram", whatsapp: "WhatsApp", web: "Web", email: "E-mail", invalid_period: "Invalid period. Check the dates.",
    volume: "Dialogs", volume_note: "How many people wrote to the bot and how many messages passed through.", dialogs: "Dialogs", dialogs_hint: "people who sent at least one message", client_messages: "Client messages", bot_messages: "Bot replies", manager_messages: "Manager messages", new_leads: "New clients", new_leads_hint: "first contact during the period", volume_chart: "Dialogs by day and channel",
    funnel: "Funnel", funnel_note: "A client's path from first message to closing. Cohort-based: a client belongs to the day they first wrote.", leads_total: "Wrote to us", leads_total_hint: "all clients during the period", engaged: "Reached a conversation", engaged_hint: "the bot replied at least once", with_contact: "Shared contact", with_contact_hint: "a phone or email usable for contact", with_cart: "Reached a cart", funnel_closed: "Closed by a manager", share_of_all: "of everyone who wrote", to_previous: "of the previous step", previous_empty: "previous step is empty", funnel_note_bottom: "Steps are not strictly nested: a client can reach a cart without sharing contact details, so the share of all clients is more reliable than conversion from the previous step.", funnel_channels: "By channel",
    web_events: "Website widget", web_note: "Actions in the website chat. This is only the chat window — the site's contact buttons and cart are not included", web_chart: "Chat actions by day", launcher_click: "Clicked the chat button", invite_click: "Clicked the pop-up prompt", web_open: "Started chat", consent_ok: "Agreed and started a conversation", contact_open: "Opened the contact form", contact_email: "Shared email", contact_phone: "Shared phone", file_upload: "Sent a photo", telegram_click: "Went to Telegram", cart_click: "Opened a cart from the bot's reply",
    carts: "Carts", carts_note: "Attempts to build a website cart for a client.", sent: "Carts built", error: "Website rejected it", error_hint: "an error on the website side", empty_cart: "Nothing to add", empty_cart_hint: "no article was found in the website catalogue", items_total: "Items total",
    managers: "Managers", managers_note: "Handing conversations to people and their response speed.", manager_open: "Open requests", manager_closed: "Closed", claimed: "Taken into work", unclaimed: "Nobody took it", claim_p50: "Half of requests are taken faster", close_p50: "Half are closed faster", measured_threads: "calculated from {n} requests out of {m}", manager_name: "Manager", replies: "Replies", threads_claimed: "Requests taken", last_reply: "Last reply",
    cost: "Cost", cost_note: "How much the bot costs to run and how quickly it replies.", estimated_cost: "Approximate cost", cost_range_note: "a range because some input is cached and costs ten times less, but the provider does not disclose how much. The truth is closer to the lower bound.", priced_coverage: "calculated from {n} replies out of {m}", unpriced_coverage: "the model price is unknown for {n} replies", tokens_in: "Sent to the bot", tokens_out: "Written by the bot", tokens_note: "Much more is sent than written — this is normal: the full bot instruction goes to the model on every request, while the reply is short.", calls_per_answer: "Model calls per reply", calls_hint: "a reply with catalogue search takes two calls", measured_answers: "calculated from {n} replies", latency_p50: "Half of replies are faster", latency_p95: "Every twentieth takes longer", speed_note: "Fast is up to 5 seconds. After 20 seconds a client usually stops waiting.", cost_chart: "Tokens by day", models: "By model", model: "Model", with_tokens: "With token data",
    routing: "How the bot replied", routing_note: "The response method affects both quality and cost.", branches: "Response method", route_reasons: "Why this response was chosen", detailed_answer: "Detailed reply", detailed_answer_hint: "expensive model with catalogue search", short_answer: "Short reply", short_answer_hint: "cheap model: greeting or small talk", followup_answer: "Follow-up", followup_answer_hint: "the bot wrote to a client who went quiet", other: "Other", show_all: "Show all", route_sticky_product: "continued a product conversation", route_greeting: "greeting", route_category: "asked about a category", route_article: "named an article", route_order: "about an order", route_long: "long message", route_human: "a person is needed", route_default: "nothing special", route_followup_1: "follow-up, first", route_followup_2: "follow-up, second", route_followup_3: "follow-up, third",
    dealers: "Dealers", dealers_note: "Notifications to responsible managers for dealer countries.", notifications: "Notifications sent", countries: "Countries", dealer_with_cart: "Of these, with a ready cart", country: "Country", ship_type: "Shipping type", responsible: "Responsible", last: "Latest",
    geo: "Geography", geo_note: "Where clients come from and what interests them. The bot fills these fields, so many are blank.", dealer: "Dealer", interests: "Product interests", product_interest: "Interest", leads: "Clients", unknown_country: "without country: {n}", unknown_dealer: "without dealer: {n}", unknown_interest: "without interest: {n}",
    quality: "Quality", quality_note: "Complaints about the bot submitted with /bug.", reports_total: "Total complaints", reports_open: "Not reviewed", statuses: "By status", categories: "By category", severities: "By severity", status: "Status", category: "Category", severity: "Severity", reports: "Complaints",
    versions: "Bot versions", versions_note: "What changed in the bot instructions and how it affected replies.", prompt_version: "Version", date: "Date", latency: "Half are faster", main_share: "Share of detailed replies", low_sample_note: "rows with fewer than 20 replies are not statistically meaningful", description_missing: "description was not saved",
    no_data: "no data", no_period_data: "no data for the period", hours_minutes: "{h} h {m} min", minutes: "{m} min", seconds: "{s} sec", milliseconds: "{n} ms", percent: "{n}%"
  }
};

const webApp = window.Telegram && window.Telegram.WebApp;
const languageCode = webApp && webApp.initDataUnsafe && webApp.initDataUnsafe.user ? webApp.initDataUnsafe.user.language_code : "";
const locale = String(languageCode || "").toLowerCase().startsWith("ru") ? "ru" : "en";
const t = strings[locale];
const numberFormat = new Intl.NumberFormat(locale === "ru" ? "ru-RU" : "en-US", { maximumFractionDigits: 2 });
let currentPreset = 30;
let statsController = null;

const elements = {
  profile: document.getElementById("profile"), title: document.getElementById("app-title"), name: document.getElementById("user-name"), role: document.getElementById("user-role"), count: document.getElementById("dialog-count"), metricLabel: document.getElementById("metric-label"),
  feedback: document.getElementById("feedback"), message: document.getElementById("message"), retry: document.getElementById("retry"), filters: document.getElementById("filters"), periodLabel: document.getElementById("period-label"), chips: document.getElementById("period-chips"), customDates: document.getElementById("custom-dates"), dateFrom: document.getElementById("date-from"), dateTo: document.getElementById("date-to"), fromLabel: document.getElementById("from-label"), toLabel: document.getElementById("to-label"), filterError: document.getElementById("filter-error"), channelLabel: document.getElementById("channel-label"), channel: document.getElementById("channel"), managerWrap: document.getElementById("manager-wrap"), managerLabel: document.getElementById("manager-label"), manager: document.getElementById("manager"), dashboard: document.getElementById("dashboard")
};

function text(key, replacements = {}) { return Object.entries(replacements).reduce((value, [name, replacement]) => value.replace(`{${name}}`, String(replacement)), t[key]); }
function node(tag, className, value) { const item = document.createElement(tag); if (className) item.className = className; if (value !== undefined) item.textContent = value; return item; }
function svgNode(tag, attributes = {}) { const item = document.createElementNS(SVG_NS, tag); Object.entries(attributes).forEach(([name, value]) => item.setAttribute(name, String(value))); return item; }
function fmt(value) { if (value === null || value === undefined) return "—"; return typeof value === "number" ? numberFormat.format(value) : String(value); }
function pct(value) { return value === null || value === undefined ? "—" : text("percent", { n: numberFormat.format(value * 100) }); }
function seconds(value) { if (value === null || value === undefined) return "—"; const total = Math.round(value); const hours = Math.floor(total / 3600); const minutes = Math.floor((total % 3600) / 60); if (hours) return text("hours_minutes", { h: hours, m: minutes }); if (minutes) return text("minutes", { m: minutes }); return text("seconds", { s: total }); }
function dateTime(value) { if (value === null || value === undefined) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : new Intl.DateTimeFormat(locale === "ru" ? "ru-RU" : "en-GB", { dateStyle: "short", timeStyle: "short" }).format(date); }
function stat(label, value, hint) { const box = node("div", "stat"); box.append(node("strong", "stat-value", fmt(value)), node("span", "metric-label", label)); if (hint) box.append(node("span", "hint", hint)); return box; }
function metrics(items) { const grid = node("div", "metrics-grid"); items.forEach((item) => grid.append(stat(item[0], item[1], item[2]))); return grid; }
function block(title, subtitle) { const section = node("section", "dashboard-block"); section.append(node("h2", "", title)); if (subtitle) section.append(node("p", "coverage", subtitle)); return section; }
function empty(period = false) { return node("p", "empty", t[period ? "no_period_data" : "no_data"]); }
function heading(value) { return node("h3", "", value); }

function table(headers, rows, lowSample) {
  const wrap = node("div", "table-wrap"); const tableElement = node("table"); const head = node("thead"); const headRow = node("tr");
  headers.forEach((header) => headRow.append(node("th", "", header))); head.append(headRow); tableElement.append(head);
  const body = node("tbody"); rows.forEach((row, index) => { const tr = node("tr", lowSample && lowSample(index) ? "low-sample" : ""); row.forEach((cell) => { const td = node("td"); if (cell instanceof Node) td.append(cell); else td.textContent = cell; tr.append(td); }); body.append(tr); });
  tableElement.append(body); wrap.append(tableElement); return wrap;
}

function chartShell(titleText, height) { const wrap = node("div", "chart"); const svg = svgNode("svg", { viewBox: `0 0 640 ${height}`, role: "img", "aria-label": titleText }); const title = svgNode("title"); title.textContent = titleText; svg.append(title); wrap.append(svg); return { wrap, svg }; }
function chartEmpty() { const wrap = node("div", "chart"); wrap.append(empty(true)); return wrap; }

function barChart(rows, series, titleText, groupKey = "day", categoryKey = "channel") {
  if (!rows.length) return chartEmpty();
  const groups = [...new Set(rows.map((row) => String(row[groupKey])))].sort(); const categories = categoryKey ? [...new Set(rows.map((row) => String(row[categoryKey])))] : series;
  const values = new Map(); rows.forEach((row) => { const key = String(row[groupKey]); if (!values.has(key)) values.set(key, {}); series.forEach((field) => { const category = categoryKey ? String(row[categoryKey]) : field; values.get(key)[category] = (values.get(key)[category] || 0) + (Number(row[field]) || 0); }); });
  const totals = groups.map((group) => Object.values(values.get(group)).reduce((sum, value) => sum + value, 0)); const max = Math.max(...totals, 1); const { wrap, svg } = chartShell(titleText, 220); const left = 8; const top = 10; const bottom = 35; const usable = 220 - top - bottom; const slot = (640 - left * 2) / groups.length; const width = Math.max(1, slot * 0.7);
  groups.forEach((group, index) => { let y = top + usable; categories.forEach((category, categoryIndex) => { const value = values.get(group)[category] || 0; const height = value / max * usable; y -= height; const rect = svgNode("rect", { x: left + index * slot + (slot - width) / 2, y, width, height, class: "chart-mark", opacity: 1 - categoryIndex * (0.65 / Math.max(categories.length, 1)) }); const itemTitle = svgNode("title"); itemTitle.textContent = `${group}: ${category} ${fmt(value)}`; rect.append(itemTitle); svg.append(rect); }); });
  const step = Math.max(1, Math.ceil(groups.length / 6)); groups.forEach((group, index) => { if (index % step !== 0 && index !== groups.length - 1) return; const label = svgNode("text", { x: left + index * slot + slot / 2, y: 210, "text-anchor": "middle" }); label.textContent = group.slice(5); svg.append(label); }); return wrap;
}

function lineChart(rows, series, titleText) {
  if (!rows.length) return chartEmpty(); const max = Math.max(...rows.flatMap((row) => series.map((field) => Number(row[field]) || 0)), 1); const { wrap, svg } = chartShell(titleText, 220); const left = 10; const top = 12; const bottom = 35; const usable = 220 - top - bottom; const stepX = rows.length > 1 ? (640 - left * 2) / (rows.length - 1) : 0;
  series.forEach((field, seriesIndex) => { const points = rows.map((row, index) => `${left + index * stepX},${top + usable - (Number(row[field]) || 0) / max * usable}`).join(" "); svg.append(svgNode("polyline", { points, fill: "none", class: "chart-mark", "stroke-width": 3, opacity: 1 - seriesIndex * 0.45 })); rows.forEach((row, index) => { const circle = svgNode("circle", { cx: left + index * stepX, cy: top + usable - (Number(row[field]) || 0) / max * usable, r: 3, class: "chart-mark", opacity: 1 - seriesIndex * 0.45 }); const itemTitle = svgNode("title"); itemTitle.textContent = `${row.day}: ${t[field] || field} ${fmt(row[field])}`; circle.append(itemTitle); svg.append(circle); }); });
  const labelStep = Math.max(1, Math.ceil(rows.length / 6)); rows.forEach((row, index) => { if (index % labelStep !== 0 && index !== rows.length - 1) return; const label = svgNode("text", { x: left + index * stepX, y: 210, "text-anchor": index === 0 ? "start" : index === rows.length - 1 ? "end" : "middle" }); label.textContent = String(row.day).slice(5); svg.append(label); }); return wrap;
}

function hBarChart(rows, labelKey, valueKey, titleText, valueFormatter = fmt) {
  if (!rows.length) return chartEmpty(); const max = Math.max(...rows.map((row) => Number(row[valueKey]) || 0), 1); const height = 28 + rows.length * 34; const { wrap, svg } = chartShell(titleText, height);
  rows.forEach((row, index) => { const y = 12 + index * 34; const label = svgNode("text", { x: 5, y: y + 9 }); label.textContent = String(row[labelKey] ?? "—"); svg.append(label); const value = svgNode("text", { x: 635, y: y + 9, "text-anchor": "end" }); value.textContent = valueFormatter(row[valueKey]); svg.append(value); svg.append(svgNode("rect", { x: 5, y: y + 15, width: Math.max(1, (Number(row[valueKey]) || 0) / max * 630), height: 9, rx: 5, class: "chart-mark" })); }); return wrap;
}

function renderVolume(volume) {
  const section = block(t.volume, t.volume_note); if (!volume.by_day.length) { section.append(empty(true)); return section; }
  section.append(metrics([[t.dialogs, volume.totals.dialogs, t.dialogs_hint], [t.client_messages, volume.totals.client_messages], [t.bot_messages, volume.totals.bot_messages], [t.manager_messages, volume.totals.manager_messages], [t.new_leads, volume.totals.new_leads, t.new_leads_hint]]));
  section.append(barChart(volume.by_day, ["dialogs"], t.volume_chart)); return section;
}

function renderFunnel(funnel) {
  const section = block(t.funnel, t.funnel_note); if (!funnel.by_day.length && !funnel.by_channel.length) { section.append(empty(true)); return section; }
  const steps = [["leads_total", "leads_total", null, null], ["engaged", "engaged", "share_engaged", "conv_engaged"], ["with_contact", "with_contact", "share_contact", "conv_contact"], ["with_cart", "with_cart", "share_cart", "conv_cart"], ["closed", "funnel_closed", "share_closed", null]];
  const funnelBars = node("div", "hbar-list"); const max = Math.max(Number(funnel.totals.leads_total) || 0, 1);
  steps.forEach(([key, labelKey, share, conversion]) => { const item = node("div"); const label = node("div", "hbar-label"); label.append(node("span", "", t[labelKey]), node("span", "", fmt(funnel.totals[key]))); const track = node("div", "hbar-track"); const fill = node("div", "hbar-fill"); fill.style.width = `${Math.max(0, Number(funnel.totals[key]) || 0) / max * 100}%`; track.append(fill); item.append(label, track); funnelBars.append(item); if (share) funnelBars.append(node("p", "conversion", `${pct(funnel.totals[share])} ${t.share_of_all}`)); if (conversion) funnelBars.append(node("p", "conversion", funnel.totals[conversion] === null ? `— ${t.previous_empty}` : `${pct(funnel.totals[conversion])} ${t.to_previous}`)); });
  section.append(funnelBars);
  section.append(node("p", "footnote", t.funnel_note_bottom), heading(t.funnel_channels));
  section.append(table([t.channel, t.leads_total, t.engaged, t.with_contact, t.with_cart, t.closed], funnel.by_channel.map((row) => [t[row.channel] || String(row.channel), fmt(row.leads_total), fmt(row.engaged), fmt(row.with_contact), fmt(row.with_cart), fmt(row.closed)]))); return section;
}

function renderWebEvents(web_events) {
  if (web_events.applicable === false) return null; const section = block(t.web_events, t.web_note); if (!web_events.by_day.length) { section.append(empty(true)); return section; }
  const events = ["launcher_click", "invite_click", "open", "consent_ok", "contact_open", "contact_email", "contact_phone", "file_upload", "telegram_click", "cart_click"]; const eventLabels = { open: "web_open" };
  section.append(metrics(events.map((event) => [t[eventLabels[event] || event], web_events.totals[event]]))); section.append(barChart(web_events.by_day, events, t.web_chart, "day", null)); return section;
}

function renderManagers(managers) {
  const section = block(t.managers, t.managers_note); const claim = managers.time_to_claim_seconds; const close = managers.time_to_close_seconds; const threadValues = Object.values(managers.threads);
  if (!managers.by_manager.length && threadValues.every((value) => value === 0 || value === null) && !claim.measured_on && !close.measured_on) { section.append(empty(true)); return section; }
  section.append(metrics([[t.manager_open, managers.threads.open], [t.manager_closed, managers.threads.closed], [t.claimed, managers.threads.claimed], [t.unclaimed, managers.threads.unclaimed], [t.claim_p50, seconds(claim.p50), text("measured_threads", { n: fmt(claim.measured_on), m: fmt(claim.of_threads) })], [t.close_p50, seconds(close.p50), text("measured_threads", { n: fmt(close.measured_on), m: fmt(close.of_threads) })]]));
  if (!managers.by_manager.length) section.append(empty()); else section.append(table([t.manager_name, t.replies, t.threads_claimed, t.last_reply], managers.by_manager.map((row) => [String(row.name ?? "—"), fmt(row.replies), fmt(row.threads_claimed), dateTime(row.last_reply_at)]))); return section;
}

function renderCost(cost) {
  if (cost === null) return null; const section = block(t.cost, t.cost_note); const money = new Intl.NumberFormat(locale === "ru" ? "ru-RU" : "en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); const usd = cost.usd || {};
  if (!cost.by_day.length) { section.append(empty(true)); return section; }
  section.append(metrics([[t.estimated_cost, usd.low === null || usd.low === undefined || usd.high === null || usd.high === undefined ? null : `$${money.format(usd.low)} – $${money.format(usd.high)}`, t.cost_range_note]]));
  section.append(node("p", "coverage", text("priced_coverage", { n: fmt(usd.priced_messages), m: fmt(cost.totals.bot_messages) }))); if (Number(usd.unpriced_messages) > 0) section.append(node("p", "coverage", text("unpriced_coverage", { n: fmt(usd.unpriced_messages) })));
  section.append(metrics([[t.tokens_in, cost.totals.tokens_in], [t.tokens_out, cost.totals.tokens_out], [t.calls_per_answer, cost.totals.llm_calls_per_answer, `${t.calls_hint} ${text("measured_answers", { n: fmt(cost.totals.llm_calls_measured_on) })}`], [t.latency_p50, cost.latency_ms.p50 === null ? null : seconds(cost.latency_ms.p50 / 1000)], [t.latency_p95, cost.latency_ms.p95 === null ? null : seconds(cost.latency_ms.p95 / 1000)]]));
  section.append(node("p", "footnote", t.tokens_note), node("p", "footnote", t.speed_note));
  section.append(lineChart(cost.by_day, ["tokens_in", "tokens_out"], t.cost_chart)); section.append(heading(t.models));
  if (!cost.by_model.length) section.append(empty()); else section.append(table([t.model, t.bot_messages, t.with_tokens, t.tokens_in, t.tokens_out], cost.by_model.map((row) => [String(row.model ?? "—"), fmt(row.bot_messages), fmt(row.with_tokens), fmt(row.tokens_in), fmt(row.tokens_out)]))); return section;
}

function routeLabel(value) { const map = { "sticky:product": "route_sticky_product", "prerouter:GREETING": "route_greeting", "prerouter:CATEGORY_RU": "route_category", "prerouter:ARTICLE": "route_article", "prerouter:ORDER": "route_order", "prerouter:LONG_MESSAGE": "route_long", "classify:needs_human": "route_human", "light:default": "route_default", "followup:stage1": "route_followup_1", "followup:stage2": "route_followup_2", "followup:stage3": "route_followup_3" }; return map[value] ? t[map[value]] : String(value); }
function renderRouting(routing) {
  const section = block(t.routing, t.routing_note); if (!routing.by_branch.length && !routing.by_route_reason.length) { section.append(empty(true)); return section; }
  const branches = { main: [t.detailed_answer, t.detailed_answer_hint], light: [t.short_answer, t.short_answer_hint], followup: [t.followup_answer, t.followup_answer_hint] }; section.append(heading(t.branches), metrics(routing.by_branch.map((row) => { const label = branches[row.branch] || [t.other]; return [label[0], pct(row.share), label[1]]; })));
  section.append(heading(t.route_reasons)); const sorted = [...routing.by_route_reason].sort((a, b) => (Number(b.bot_messages) || 0) - (Number(a.bot_messages) || 0)); const chartHost = node("div"); const render = (showAll) => { const rows = (showAll ? sorted : sorted.slice(0, 10)).map((row) => ({ ...row, label: routeLabel(row.route_reason) })); chartHost.replaceChildren(hBarChart(rows, "label", "bot_messages", t.route_reasons)); if (!showAll && sorted.length > 10) { const button = node("button", "show-all", t.show_all); button.type = "button"; button.addEventListener("click", () => render(true)); chartHost.append(button); } }; render(false); section.append(chartHost); return section;
}

function dataList(rows, labelKey) { if (!rows.length) return empty(); const list = node("ul", "data-list"); rows.forEach((row) => { const li = node("li"); li.append(node("span", "", String(row[labelKey] ?? "—")), node("span", "", fmt(row.leads ?? row.reports))); list.append(li); }); return list; }
function renderCarts(carts) { const section = block(t.carts, t.carts_note); if (!carts.by_day.length && !carts.by_channel.length) { section.append(empty(true)); return section; } section.append(metrics([[t.sent, carts.totals.sent], [t.error, carts.totals.error, t.error_hint], [t.empty_cart, carts.totals.empty, t.empty_cart_hint], [t.items_total, carts.totals.items_total]])); return section; }
function renderDealers(dealers) { const section = block(t.dealers, t.dealers_note); if (!dealers.by_country.length && !dealers.by_manager.length) { section.append(empty(true)); return section; } section.append(metrics([[t.notifications, dealers.totals.notifications], [t.countries, dealers.totals.countries], [t.dealer_with_cart, dealers.totals.with_cart]])); section.append(heading(t.countries), table([t.country, t.ship_type, t.notifications], dealers.by_country.map((row) => [String(row.country ?? "—"), String(row.ship_type ?? "—"), fmt(row.notifications)]))); section.append(heading(t.responsible), table([t.responsible, t.notifications, t.last], dealers.by_manager.map((row) => [String(row.manager ?? "—"), fmt(row.notifications), dateTime(row.last_at)]))); return section; }
function renderGeo(geo) { const section = block(t.geo, t.geo_note); const listsEmpty = !geo.by_country.length && !geo.by_dealer.length && !geo.by_product_interest.length; const unknownEmpty = Object.values(geo.unknown).every((value) => value === 0 || value === null); if (listsEmpty && unknownEmpty) { section.append(empty(true)); return section; } const columns = node("div", "columns"); [[t.countries, geo.by_country, "country"], [t.dealers, geo.by_dealer, "dealer"], [t.interests, geo.by_product_interest, "product_interest"]].forEach(([title, rows, key]) => { const column = node("div"); column.append(heading(title), dataList(rows, key)); columns.append(column); }); section.append(columns, node("p", "footnote", text("unknown_country", { n: fmt(geo.unknown.country) })), node("p", "footnote", text("unknown_dealer", { n: fmt(geo.unknown.dealer) })), node("p", "footnote", text("unknown_interest", { n: fmt(geo.unknown.product_interest) }))); return section; }

function renderQuality(quality) { const section = block(t.quality, t.quality_note); if (quality.total === 0 && !quality.by_status.length && !quality.by_category.length && !quality.by_severity.length) { section.append(empty(true)); return section; } section.append(metrics([[t.reports_total, quality.total], [t.reports_open, quality.open_count]])); const columns = node("div", "columns"); [[t.statuses, quality.by_status, "status"], [t.categories, quality.by_category, "category"], [t.severities, quality.by_severity, "severity"]].forEach(([title, rows, key]) => { const column = node("div"); column.append(heading(title), dataList(rows, key)); columns.append(column); }); section.append(columns); return section; }

function versionCell(row) { const wrap = node("div"); wrap.append(node("div", "", String(row.prompt_version ?? "—")), node("span", "hint", String(row.title || t.description_missing))); return wrap; }
function renderVersions(versions) { const section = block(t.versions, t.versions_note); if (!versions.length) { section.append(empty(true)); return section; } section.append(table([t.prompt_version, t.date, t.bot_messages, t.dialogs, t.latency, t.calls_per_answer, t.main_share], versions.map((row) => [versionCell(row), String(row.released_on ?? "—"), fmt(row.bot_messages), fmt(row.dialogs), row.latency_p50 === null ? "—" : seconds(row.latency_p50 / 1000), fmt(row.llm_calls_per_answer), pct(row.main_share)]), (index) => versions[index].low_sample === true)); section.append(node("p", "footnote", t.low_sample_note)); return section; }

function renderDashboard(data) {
  const blocks = [renderVolume(data.volume), renderFunnel(data.funnel), renderWebEvents(data.web_events), renderCarts(data.carts), renderManagers(data.managers), renderCost(data.cost), renderRouting(data.routing), renderDealers(data.dealers), renderGeo(data.geo), renderQuality(data.quality), renderVersions(data.versions)].filter(Boolean);
  elements.dashboard.replaceChildren(...blocks); elements.dashboard.hidden = false;
}

function renderSkeletons() { elements.dashboard.replaceChildren(...Array.from({ length: 11 }, () => node("section", "dashboard-block skeleton"))); elements.dashboard.hidden = false; }
function applyTheme() { const theme = (webApp && webApp.themeParams) || {}; const variables = { "--tg-bg": theme.bg_color, "--tg-text": theme.text_color, "--tg-hint": theme.hint_color, "--tg-link": theme.link_color, "--tg-button": theme.button_color, "--tg-button-text": theme.button_text_color, "--tg-secondary-bg": theme.secondary_bg_color }; Object.entries(variables).forEach(([name, value]) => { if (value) document.documentElement.style.setProperty(name, value); }); }
function renderError(key, canRetry) { elements.feedback.hidden = false; elements.message.textContent = t[key] || t.internal; elements.retry.textContent = t.retry; elements.retry.hidden = !canRetry; elements.dashboard.hidden = true; }
function clearError() { elements.feedback.hidden = true; elements.retry.hidden = true; }

async function request(path) {
  const response = await fetch(API + path, { headers: { "X-Tg-Init-Data": webApp.initData }, signal: path.startsWith("/stats") && statsController ? statsController.signal : undefined }); const body = await response.json().catch(() => ({}));
  if (response.status === RESPONSE_STATUS.success) return body; const error = String(body.error || "internal"); const known = Object.prototype.hasOwnProperty.call(t, error) ? error : "internal"; const canRetry = response.status >= RESPONSE_STATUS.internal || response.status === RESPONSE_STATUS.rate_limited; const failure = new Error(known); failure.key = known; failure.canRetry = canRetry; throw failure;
}

function moscowToday() { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Moscow", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const values = Object.fromEntries(parts.map((part) => [part.type, part.value])); return `${values.year}-${values.month}-${values.day}`; }
function addDays(dateText, delta) { const [year, month, day] = dateText.split("-").map(Number); const date = new Date(Date.UTC(year, month - 1, day + delta)); return date.toISOString().slice(0, 10); }
function presetDates(days) { const to = moscowToday(); return { from: addDays(to, -(days - 1)), to }; }
function validDates(from, to) { if (!from || !to || from > to) return false; const start = Date.parse(`${from}T00:00:00Z`); const end = Date.parse(`${to}T00:00:00Z`); return Number.isFinite(start) && Number.isFinite(end) && (end - start) / 86400000 <= 365; }
function statsParams() { const params = new URLSearchParams(); const dates = currentPreset === "custom" ? { from: elements.dateFrom.value, to: elements.dateTo.value } : presetDates(currentPreset); params.set("from", dates.from); params.set("to", dates.to); params.set("channel", elements.channel.value); if (elements.manager.value) params.set("manager", elements.manager.value); return params; }

function updateManagers(names) { const selected = elements.manager.value; elements.manager.replaceChildren(); const all = node("option", "", t.all); all.value = ""; elements.manager.append(all); names.forEach((name) => { const option = node("option", "", String(name)); option.value = String(name); elements.manager.append(option); }); elements.manager.value = names.includes(selected) ? selected : ""; elements.managerWrap.hidden = names.length === 0; }

async function loadStats() {
  const dates = currentPreset === "custom" ? { from: elements.dateFrom.value, to: elements.dateTo.value } : presetDates(currentPreset); if (!validDates(dates.from, dates.to)) { elements.filterError.textContent = t.invalid_period; elements.filterError.hidden = false; return; }
  elements.filterError.hidden = true; clearError(); renderSkeletons(); if (statsController) statsController.abort(); statsController = new AbortController();
  try { const data = await request(`/stats?${statsParams().toString()}`); updateManagers(data.managers.known_managers); renderDashboard(data); } catch (error) { if (error.name !== "AbortError") renderError(error.key || "internal", error.canRetry !== false); }
}

function setupFilters() {
  elements.periodLabel.textContent = t.period; elements.fromLabel.textContent = t.from; elements.toLabel.textContent = t.to; elements.channelLabel.textContent = t.channel; elements.managerLabel.textContent = t.manager_filter;
  [[7, "days_7"], [30, "days_30"], [90, "days_90"], ["custom", "custom"]].forEach(([value, key]) => { const button = node("button", "chip", t[key]); button.type = "button"; button.dataset.period = String(value); button.setAttribute("aria-pressed", value === 30 ? "true" : "false"); button.addEventListener("click", () => { currentPreset = value; [...elements.chips.children].forEach((chip) => chip.setAttribute("aria-pressed", chip === button ? "true" : "false")); elements.customDates.hidden = value !== "custom"; if (value === "custom") { const dates = presetDates(30); if (!elements.dateFrom.value) elements.dateFrom.value = dates.from; if (!elements.dateTo.value) elements.dateTo.value = dates.to; } loadStats(); }); elements.chips.append(button); });
  [["all", "all"], ["telegram", "telegram"], ["whatsapp", "whatsapp"], ["web", "web"], ["email", "email"]].forEach(([value, key]) => { const option = node("option", "", t[key]); option.value = value; elements.channel.append(option); }); updateManagers([]);
  elements.channel.addEventListener("change", loadStats); elements.manager.addEventListener("change", loadStats); elements.dateFrom.addEventListener("change", loadStats); elements.dateTo.addEventListener("change", loadStats); elements.filters.addEventListener("submit", (event) => event.preventDefault()); elements.filters.hidden = false;
}

async function loadProfile() {
  elements.title.textContent = t.app_title; elements.name.textContent = t.loading; elements.role.textContent = ""; elements.count.textContent = "—"; elements.metricLabel.textContent = t.today_dialogs; clearError();
  if (!webApp || !webApp.initData) { elements.profile.hidden = true; renderError("not_telegram", false); return; }
  try { const profile = await request("/me"); elements.profile.hidden = false; elements.name.textContent = String(profile.name || ""); elements.role.textContent = t[profile.role] || t.unknown_role; elements.count.textContent = fmt(profile.today_dialogs); setupFilters(); await loadStats(); } catch (error) { elements.profile.hidden = true; renderError(error.key || "internal", error.canRetry !== false); }
}

elements.retry.addEventListener("click", () => { if (elements.filters.hidden) loadProfile(); else loadStats(); });
document.title = t.app_title; applyTheme();
if (webApp) { webApp.ready(); webApp.expand(); webApp.onEvent("themeChanged", applyTheme); }
loadProfile();
